<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>Editor_PCBasket___Mou</RootNamespace>
    <AssemblyName>Editor PCBasket - Mou</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>icono.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Resources\Lexend.ttf" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\EpcbDatabaseServiceEntityFramework\EpcbDatabaseServiceEntityFramework.csproj" />
    <ProjectReference Include="..\EpcbModel\EpcbModel.csproj" />
    <ProjectReference Include="..\EpcbUtils\EpcbUtils.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="icono.ico" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Graficos\medfoto.bmp">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Graficos\minifoto.bmp">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Graficos\nanofoto.bmp">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="mspaint.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Resource Include="Resources\logo.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommonServiceLocator" Version="2.0.2" />
    <PackageReference Include="Config.Net" Version="5.2.0" />
    <PackageReference Include="ControlzEx" Version="4.3.0" />
    <PackageReference Include="gong-wpf-dragdrop" Version="2.2.0" />
    <PackageReference Include="MahApps.Metro" Version="2.0.0" />
    <PackageReference Include="MaterialDesignColors" Version="3.1.0" />
    <PackageReference Include="MaterialDesignThemes" Version="5.1.0" />
    <PackageReference Include="MaterialDesignThemes.MahApps" Version="3.1.0" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.6" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.39" />
    <PackageReference Include="Ookii.Dialogs.Wpf" Version="5.0.1" />
    <PackageReference Include="Prism.Core" Version="8.1.97" />
    <PackageReference Include="Prism.Unity" Version="8.1.97" />
    <PackageReference Include="Prism.Wpf" Version="8.1.97" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="Unity.Abstractions" Version="5.11.7" />
    <PackageReference Include="Unity.Container" Version="5.11.11" />
    <PackageReference Include="Microsoft.AspNetCore.SystemWebAdapters" Version="1.3.0" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" />
  </ItemGroup>
  <PropertyGroup>
    <PostBuildEvent>
    if not exist "$(TargetDir)x86" md "$(TargetDir)x86"
    xcopy /s /y "$(SolutionDir)packages\Microsoft.SqlServer.Compact.4.0.8876.1\NativeBinaries\x86\*.*" "$(TargetDir)x86"
    if not exist "$(TargetDir)amd64" md "$(TargetDir)amd64"
    xcopy /s /y "$(SolutionDir)packages\Microsoft.SqlServer.Compact.4.0.8876.1\NativeBinaries\amd64\*.*" "$(TargetDir)amd64"</PostBuildEvent>
  </PropertyGroup>
</Project>